# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # creating hash from the given hash_string
  hash_string=ENV["HASH_TABLE_STRING"]
  arr = hash_string.split(',')
  hash = {}
  arr.each do |e|
    pair = e.split(':')
    hash[pair[0]] = pair[1]
  end

  #vagrant-box-config
  config.vm.box = ENV["OS_IMAGE"] 
  config.vm.provision "shell", path: ENV["SCRIPT"], env: hash
  config.vm.synced_folder ENV["SYNC_FOLDER"], "/home/gov/sync_folder", disabled:false
  config.vm.synced_folder ".", "/vagrant", disabled:true
  config.vm.network "private_network", ip: ENV["HOST_ONLY_IP"]
  config.vm.network "public_network", bridge: [
    "Realtek PCIe GbE Family Controller",
    "Intel(R) Wi-Fi 6 AX201 160MHz"
  ]
  config.vm.provider "virtualbox" do |vb|
    vb.name = ENV["VM_NAME"]
    vb.memory = ENV["RAM"]
    vb.cpus = ENV["CPU"]
  end

  if ENV["DISK_SIZE_PRIMARY"] != ""
    config.vm.disk :disk, size: ENV["DISK_SIZE_PRIMARY"], primary: true
  end

  if ENV["DISK_SIZE_SECOND"] != ""
    config.vm.disk :disk, size: ENV["DISK_SIZE_SECOND"], name: "sdb"
  end

end
